---
- name: Install dependencies
  apt:
    name:
      - openjdk-11-jre-headless
      - unzip
    state: present

- name: SonarQube user Create
  user:
    name: sonarqube
    shell: /bin/bash
    create_home: yes

- name: Download SonarQube
  get_url:
    url: "{{ sonarqube_download_url }}"
    dest: "/tmp/sonarqube-{{ sonarqube_version }}.zip"

- name: Extract the SonarQube
  unarchive:
    src: "/tmp/sonarqube-{{ sonarqube_version }}.zip"
    dest: "/opt/"
    remote_src: yes
    creates: "/opt/sonarqube-{{ sonarqube_version }}"

- name: symbolic link
  file:
    src: "/opt/sonarqube-{{ sonarqube_version }}"
    dest: "/opt/sonarqube"
    state: link

- name: permissions
  file:
    path: "/opt/sonarqube"
    state: directory
    mode: 0755
    recurse: yes

- name: environment variables
  lineinfile:
    dest: /etc/environment
    line: 'SONAR_HOME="/opt/sonarqube"'
  notify:
    - Reload systemd

- name: Set up systemd service
  template:
    src: sonarqube.service.j2
    dest: /etc/systemd/system/sonarqube.service
  notify:
    - Reload systemd

- name: Start SonarQube service
  service:
    name: sonarqube
    state: started
    enabled: yes

- name: Wait for SonarQube to start
  wait_for:
    port: 9000
    timeout: 180
